---
abstract: 'A DEPRECATED event-driven RTF Parser'
author:
  - 'Peter Sergeant <pete@clueball.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RTF-Parser
requires:
  ExtUtils::MakeMaker: '6.30'
  RTF::Tokenizer: '1.16'
version: '1.12'
